services:
    web:
        build: ./web
        restart: unless-stopped
        volumes:
            - ./web:/app
            - node_modules_web:/app/node_modules
        working_dir: /app
        env_file:
            - .env
        command: npm run production
        networks:
            - atesdoc
    api:
        build: ./api
        restart: unless-stopped
        volumes:
            - ./api:/app
            - node_modules_api:/app/node_modules
        working_dir: /app
        env_file:
            - .env
        command: npm run production
        networks:
            - atesdoc
    chrome:
        image: 'browserless/chrome:latest'
        restart: unless-stopped
        shm_size: '2gb'
        environment:
            - MAX_CONCURRENT_SESSIONS=1
            - CONNECTION_TIMEOUT=60000
            - CHROME_REFRESH_TIME=3600000
            - DEFAULT_LAUNCH_ARGS=["--disable-dev-shm-usage","--no-sandbox","--disable-setuid-sandbox","--disable-gpu"]
        networks:
            - atesdoc
    nginx:
        image: pswerlang/nginx-auto-ssl
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx:/etc/nginx/conf.d
        environment:
            - SITES=${WEBSITE_URL}=web:3000;${API_URL}=api:8080
            - ALLOWED_DOMAINS=${PRODUCTION_DOMAIN}
            - FORCE_HTTPS=true
        networks:
            - atesdoc
        depends_on:
            - web
            - api
        logging:
            options:
                max-size: "10m"
volumes:
    node_modules_web:
    node_modules_api:
    chrome_data:
networks:
    atesdoc:
        name: atesdoc
