services:
    web:
        build: ./web
        restart: unless-stopped
        volumes:
            - ./web:/app
            - node_modules_web:/app/node_modules
        working_dir: /app
        env_file:
            - .env
        # ports:
        #     - 127.0.0.1:80:80
        command: npm run ${NODE_ENV}
        networks:
            - atesdoc
    api:
        build: ./api
        restart: unless-stopped
        volumes:
            - ./api:/app
            - node_modules_api:/app/node_modules
        working_dir: /app
        env_file:
            - .env
        # ports:
        #     - 127.0.0.1:8080:8080
        command: npm run $NODE_ENV
        # command: tail -f /dev/null
        networks:
            - atesdoc
    chrome:
        image: 'browserless/chrome:latest'
        restart: unless-stopped
        networks:
            - atesdoc
volumes:
    node_modules_web:
    node_modules_api:
    chrome_data:
networks:
    atesdoc:
        name: atesdoc
